name 'cesnet-hive'
version '0.15.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hive'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Apache Hive Puppet Module'
description 'Apache Hive Puppet Module'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-hive'

dependency 'puppetlabs/stdlib', '>=1.0.0 <7.0.0'
dependency 'cesnet/hadoop', '>=0.9.4 <4.0.0'
dependency 'cesnet/hadoop_lib', '>=0.4.0 <1.0.0'
